[
    {
        "id": "e92a34f9.129ef8",
        "type": "tab",
        "label": "Netatmo 2"
    },
    {
        "id": "142317ce.6984a8",
        "type": "inject",
        "z": "e92a34f9.129ef8",
        "name": "",
        "topic": "5 Minutes Timer",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "60",
        "crontab": "",
        "once": false,
        "x": 147,
        "y": 34,
        "wires": [
            [
                "fcbf619d.a110d"
            ]
        ]
    },
    {
        "id": "fcbf619d.a110d",
        "type": "get stations data",
        "z": "e92a34f9.129ef8",
        "name": "",
        "creds": "b71bfc6f.5b329",
        "x": 359,
        "y": 34,
        "wires": [
            [
                "aac0a279.9ac27",
                "8542f798.ba2988",
                "88297ea5.3c832"
            ]
        ]
    },
    {
        "id": "aac0a279.9ac27",
        "type": "function",
        "z": "e92a34f9.129ef8",
        "name": "Main-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\nvar msg6 = {};\nvar msg7 = {};\nvar msg8 = {};\nvar msg9 = {};\n\nmsg1.payload = msg.payload.devices[0].dashboard_data.Pressure;\nmsg2.payload = msg.payload.devices[0].dashboard_data.Noise;\nmsg3.payload = msg.payload.devices[0].dashboard_data.Temperature;\nmsg4.payload = msg.payload.devices[0].dashboard_data.temp_trend;\nmsg5.payload = msg.payload.devices[0].dashboard_data.Humidity;\nmsg6.payload = msg.payload.devices[0].dashboard_data.CO2;\nmsg7.payload = msg.payload.devices[0].dashboard_data.pressure_trend;\nmsg8.payload = msg.payload.devices[0].dashboard_data.min_temp;\nmsg9.payload = msg.payload.devices[0].dashboard_data.max_temp;\n\nreturn [msg1,msg2,msg3,msg4,msg5,msg6,msg7,msg8,msg9];",
        "outputs": "9",
        "noerr": 0,
        "x": 729,
        "y": 151.5,
        "wires": [
            [
                "bf17487e.7665c8",
                "1f383311.f2204d"
            ],
            [
                "745f6748.75aff8",
                "a06c0d4.9bea9f"
            ],
            [
                "ba2b71bd.aad0d",
                "1d9bc0ec.a3c82f"
            ],
            [
                "ff6dd2d0.28b09"
            ],
            [
                "410edd32.c6a4d4",
                "48d0bef1.a71b2"
            ],
            [
                "fb449ae0.ae22a8",
                "8b763e2a.aec3b"
            ],
            [
                "e8a63f2c.1509c"
            ],
            [
                "23e43a89.da3466"
            ],
            [
                "f5783966.b715b8"
            ]
        ]
    },
    {
        "id": "8542f798.ba2988",
        "type": "function",
        "z": "e92a34f9.129ef8",
        "name": "Outer-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\n\nmsg1.payload = msg.payload.devices[0].modules[0].dashboard_data.Temperature;\nmsg2.payload = msg.payload.devices[0].modules[0].dashboard_data.temp_trend;\nmsg3.payload = msg.payload.devices[0].modules[0].dashboard_data.Humidity;\nmsg4.payload = msg.payload.devices[0].modules[0].dashboard_data.min_temp;\nmsg5.payload = msg.payload.devices[0].modules[0].dashboard_data.max_temp;\n\nreturn [msg1,msg2,msg3,msg4,msg5];",
        "outputs": "5",
        "noerr": 0,
        "x": 582,
        "y": 434,
        "wires": [
            [
                "3f6b14ab.abb39c",
                "b3908ee5.712a2"
            ],
            [
                "5f91b458.df4b1c"
            ],
            [
                "db5477f.d679788",
                "b7766fd9.988e"
            ],
            [
                "dc7481a2.9772e"
            ],
            [
                "2bb0cca2.d71b64"
            ]
        ]
    },
    {
        "id": "88297ea5.3c832",
        "type": "function",
        "z": "e92a34f9.129ef8",
        "name": "Inner-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\nvar msg6 = {};\n\nmsg1.payload = msg.payload.devices[0].modules[1].dashboard_data.Temperature;\nmsg2.payload = msg.payload.devices[0].modules[1].dashboard_data.temp_trend;\nmsg3.payload = msg.payload.devices[0].modules[1].dashboard_data.Humidity;\nmsg4.payload = msg.payload.devices[0].modules[1].dashboard_data.min_temp;\nmsg5.payload = msg.payload.devices[0].modules[1].dashboard_data.max_temp;\nmsg6.payload = msg.payload.devices[0].modules[1].dashboard_data.CO2;\n\nreturn [msg1,msg2,msg3,msg4,msg5,msg6];",
        "outputs": "6",
        "noerr": 0,
        "x": 112,
        "y": 600,
        "wires": [
            [
                "66484c54.46a504",
                "5de54f28.a4d3d"
            ],
            [
                "89ab1ce2.406d5"
            ],
            [
                "e6138164.81385",
                "f6f44711.901ef8"
            ],
            [
                "e2738a65.ac1b18"
            ],
            [
                "783d7240.7f673c"
            ],
            [
                "6aa09f0.0503d6",
                "8dd45100.4976f"
            ]
        ]
    },
    {
        "id": "bf17487e.7665c8",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 10,
        "width": "3",
        "height": "3",
        "name": "Luftdruck",
        "label": "Luftdruck",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1057,
        "y": 20,
        "wires": []
    },
    {
        "id": "1f383311.f2204d",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Luftdruck",
        "group": "b4493612.d38fe8",
        "order": 11,
        "width": "6",
        "height": "3",
        "label": "Luftdruck",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1062,
        "y": 54,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "745f6748.75aff8",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 12,
        "width": "3",
        "height": "3",
        "name": "Lautstärke",
        "label": "Lautstärke",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1071,
        "y": 87,
        "wires": []
    },
    {
        "id": "a06c0d4.9bea9f",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Lautstärke",
        "group": "b4493612.d38fe8",
        "order": 13,
        "width": "6",
        "height": "3",
        "label": "Lautstärke",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1073,
        "y": 125,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "ba2b71bd.aad0d",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "b4493612.d38fe8",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Termperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "40",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 1072,
        "y": 164,
        "wires": []
    },
    {
        "id": "1d9bc0ec.a3c82f",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "b4493612.d38fe8",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperatur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1071,
        "y": 202,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "ff6dd2d0.28b09",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 3,
        "width": "3",
        "height": "1",
        "name": "Temp Trend",
        "label": "Temperatur Trend",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1071,
        "y": 240,
        "wires": []
    },
    {
        "id": "410edd32.c6a4d4",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "b4493612.d38fe8",
        "order": 6,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "65",
        "seg2": "70",
        "x": 1081,
        "y": 276,
        "wires": []
    },
    {
        "id": "48d0bef1.a71b2",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "b4493612.d38fe8",
        "order": 7,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1079,
        "y": 311,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "fb449ae0.ae22a8",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "CO2",
        "group": "b4493612.d38fe8",
        "order": 8,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "CO2",
        "label": "PPM",
        "format": "{{value}}",
        "min": 0,
        "max": "5000",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "1000",
        "seg2": "2000",
        "x": 1049,
        "y": 347,
        "wires": []
    },
    {
        "id": "8b763e2a.aec3b",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "CO2",
        "group": "b4493612.d38fe8",
        "order": 9,
        "width": "6",
        "height": "3",
        "label": "CO2",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1049,
        "y": 388,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "e8a63f2c.1509c",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 14,
        "width": 0,
        "height": 0,
        "name": "Druck Trend",
        "label": "Druck Trend",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1069,
        "y": 434,
        "wires": []
    },
    {
        "id": "23e43a89.da3466",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1056,
        "y": 471,
        "wires": []
    },
    {
        "id": "f5783966.b715b8",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "b4493612.d38fe8",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1065,
        "y": 508,
        "wires": []
    },
    {
        "id": "66484c54.46a504",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "97160849.0e5d18",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Temperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "40",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 379,
        "y": 452,
        "wires": []
    },
    {
        "id": "5de54f28.a4d3d",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "97160849.0e5d18",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperatur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 379,
        "y": 487,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "89ab1ce2.406d5",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "97160849.0e5d18",
        "order": 3,
        "width": "3",
        "height": "1",
        "name": "Temp Trend",
        "label": "Temperatur Trend",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 378,
        "y": 523,
        "wires": []
    },
    {
        "id": "e2738a65.ac1b18",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "97160849.0e5d18",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 365,
        "y": 632,
        "wires": []
    },
    {
        "id": "783d7240.7f673c",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "97160849.0e5d18",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 374,
        "y": 668,
        "wires": []
    },
    {
        "id": "e6138164.81385",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "97160849.0e5d18",
        "order": 0,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "60",
        "seg2": "65",
        "x": 388,
        "y": 558,
        "wires": []
    },
    {
        "id": "f6f44711.901ef8",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "97160849.0e5d18",
        "order": 0,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 390,
        "y": 597,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "6aa09f0.0503d6",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "CO2",
        "group": "97160849.0e5d18",
        "order": 0,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "CO2",
        "label": "ppm",
        "format": "{{value}}",
        "min": 0,
        "max": "5000",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "1000",
        "seg2": "1500",
        "x": 355,
        "y": 707,
        "wires": []
    },
    {
        "id": "8dd45100.4976f",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "CO2",
        "group": "97160849.0e5d18",
        "order": 0,
        "width": "6",
        "height": "3",
        "label": "CO2",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 355,
        "y": 749,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "3f6b14ab.abb39c",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "9d48da59.28b8e8",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Temperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "50",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 820,
        "y": 382,
        "wires": []
    },
    {
        "id": "b3908ee5.712a2",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Temperatur",
        "group": "9d48da59.28b8e8",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperartur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 818,
        "y": 417,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "5f91b458.df4b1c",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "9d48da59.28b8e8",
        "order": 3,
        "width": "3",
        "height": "1",
        "name": "Temp Trend",
        "label": "Temp Trend",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 818,
        "y": 454,
        "wires": []
    },
    {
        "id": "dc7481a2.9772e",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "9d48da59.28b8e8",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 807,
        "y": 491,
        "wires": []
    },
    {
        "id": "2bb0cca2.d71b64",
        "type": "ui_text",
        "z": "e92a34f9.129ef8",
        "group": "9d48da59.28b8e8",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 817,
        "y": 531,
        "wires": []
    },
    {
        "id": "db5477f.d679788",
        "type": "ui_gauge",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "9d48da59.28b8e8",
        "order": 6,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "60",
        "seg2": "70",
        "x": 826,
        "y": 570,
        "wires": []
    },
    {
        "id": "b7766fd9.988e",
        "type": "ui_chart",
        "z": "e92a34f9.129ef8",
        "name": "Luftfeuchtigkeit",
        "group": "9d48da59.28b8e8",
        "order": 7,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 827,
        "y": 607,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "b71bfc6f.5b329",
        "type": "configNode",
        "z": "",
        "client_id": "",
        "client_secret": "",
        "username": "",
        "password": "",
        "device_id": ""
    },
    {
        "id": "b4493612.d38fe8",
        "type": "ui_group",
        "z": "",
        "name": "Wohnzimmer",
        "tab": "56d2e2c7.55c26c",
        "disp": true,
        "width": "9"
    },
    {
        "id": "97160849.0e5d18",
        "type": "ui_group",
        "z": "",
        "name": "Schlafzimmer",
        "tab": "56d2e2c7.55c26c",
        "order": 2,
        "disp": true,
        "width": "9"
    },
    {
        "id": "9d48da59.28b8e8",
        "type": "ui_group",
        "z": "",
        "name": "Außen",
        "tab": "56d2e2c7.55c26c",
        "order": 3,
        "disp": true,
        "width": "9"
    },
    {
        "id": "56d2e2c7.55c26c",
        "type": "ui_tab",
        "z": "",
        "name": "Netatmo",
        "icon": "dashboard"
    }
]
