[
    {
        "id": "e78aafe0.1bebe",
        "type": "inject",
        "z": "fd02760a.0d90c8",
        "name": "",
        "topic": "5 Minutes Timer",
        "payload": "true",
        "payloadType": "bool",
        "repeat": "60",
        "crontab": "",
        "once": false,
        "x": 147,
        "y": 34,
        "wires": [
            [
                "343f2aa3.949886"
            ]
        ]
    },
    {
        "id": "343f2aa3.949886",
        "type": "get stations data",
        "z": "fd02760a.0d90c8",
        "name": "",
        "creds": "b71bfc6f.5b329",
        "x": 359,
        "y": 34,
        "wires": [
            [
                "c6f15ad9.875ee8",
                "5437e77c.4a0498",
                "76ebd9e8.6bf418"
            ]
        ]
    },
    {
        "id": "c6f15ad9.875ee8",
        "type": "function",
        "z": "fd02760a.0d90c8",
        "name": "Main-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\nvar msg6 = {};\nvar msg7 = {};\nvar msg8 = {};\nvar msg9 = {};\n\nmsg1.payload = msg.payload.devices[0].dashboard_data.Pressure;\nmsg2.payload = msg.payload.devices[0].dashboard_data.Noise;\nmsg3.payload = msg.payload.devices[0].dashboard_data.Temperature;\n//msg4.payload = msg.payload.devices[0].dashboard_data.temp_trend;\nmsg5.payload = msg.payload.devices[0].dashboard_data.Humidity;\nmsg6.payload = msg.payload.devices[0].dashboard_data.CO2;\n//msg7.payload = msg.payload.devices[0].dashboard_data.pressure_trend;\nmsg8.payload = msg.payload.devices[0].dashboard_data.min_temp;\nmsg9.payload = msg.payload.devices[0].dashboard_data.max_temp;\n\nreturn [msg1,msg2,msg3,msg4,msg5,msg6,msg7,msg8,msg9];\n",
        "outputs": "9",
        "noerr": 0,
        "x": 729,
        "y": 151.5,
        "wires": [
            [
                "fac5726b.9319",
                "15e30fa.84583f"
            ],
            [
                "a45580c3.9c69a",
                "da6d50be.0d135"
            ],
            [
                "77f1919d.e6b84",
                "1dc74cff.abb263"
            ],
            [],
            [
                "35f5f08.ee1651",
                "b82e175f.ff76a8"
            ],
            [
                "1305073b.180619",
                "aea672ad.41199"
            ],
            [],
            [
                "d091f10d.26b4"
            ],
            [
                "a0f2d627.a87e48"
            ]
        ]
    },
    {
        "id": "5437e77c.4a0498",
        "type": "function",
        "z": "fd02760a.0d90c8",
        "name": "Outer-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\n\nmsg1.payload = msg.payload.devices[0].modules[0].dashboard_data.Temperature;\n//msg2.payload = msg.payload.devices[0].modules[0].dashboard_data.temp_trend;\nmsg3.payload = msg.payload.devices[0].modules[0].dashboard_data.Humidity;\nmsg4.payload = msg.payload.devices[0].modules[0].dashboard_data.min_temp;\nmsg5.payload = msg.payload.devices[0].modules[0].dashboard_data.max_temp;\n\nreturn [msg1,msg2,msg3,msg4,msg5];",
        "outputs": "5",
        "noerr": 0,
        "x": 582,
        "y": 434,
        "wires": [
            [
                "322a090a.328106",
                "8d284696.050368"
            ],
            [],
            [
                "353985a1.6b0a6a",
                "6a103af.2e7cbc4"
            ],
            [
                "3799e200.1d7f6e"
            ],
            [
                "1c1d6c41.73c5d4"
            ]
        ]
    },
    {
        "id": "76ebd9e8.6bf418",
        "type": "function",
        "z": "fd02760a.0d90c8",
        "name": "Inner-Module",
        "func": "var msg1 = {};\nvar msg2 = {};\nvar msg3 = {};\nvar msg4 = {};\nvar msg5 = {};\nvar msg6 = {};\n\nmsg1.payload = msg.payload.devices[0].modules[1].dashboard_data.Temperature;\n//msg2.payload = msg.payload.devices[0].modules[1].dashboard_data.temp_trend;\nmsg3.payload = msg.payload.devices[0].modules[1].dashboard_data.Humidity;\nmsg4.payload = msg.payload.devices[0].modules[1].dashboard_data.min_temp;\nmsg5.payload = msg.payload.devices[0].modules[1].dashboard_data.max_temp;\nmsg6.payload = msg.payload.devices[0].modules[1].dashboard_data.CO2;\n\nreturn [msg1,msg2,msg3,msg4,msg5,msg6];",
        "outputs": "6",
        "noerr": 0,
        "x": 112,
        "y": 600,
        "wires": [
            [
                "12134281.6912fd",
                "5beb13db.4fb49c"
            ],
            [],
            [
                "7b84810f.594f",
                "297a3afd.337986"
            ],
            [
                "d3d7895a.133a48"
            ],
            [
                "d509cc3f.9922c"
            ],
            [
                "258e1ef9.a6b5a2",
                "dde7f0c1.0ef08"
            ]
        ]
    },
    {
        "id": "fac5726b.9319",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "18f5a3cf.c12dbc",
        "order": 10,
        "width": "3",
        "height": "3",
        "name": "Luftdruck",
        "label": "Luftdruck",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1057,
        "y": 20,
        "wires": []
    },
    {
        "id": "15e30fa.84583f",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Luftdruck",
        "group": "18f5a3cf.c12dbc",
        "order": 11,
        "width": "6",
        "height": "3",
        "label": "Luftdruck",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1062,
        "y": 54,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "a45580c3.9c69a",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "18f5a3cf.c12dbc",
        "order": 12,
        "width": "3",
        "height": "3",
        "name": "Lautstärke",
        "label": "Lautstärke",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1071,
        "y": 87,
        "wires": []
    },
    {
        "id": "da6d50be.0d135",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Lautstärke",
        "group": "18f5a3cf.c12dbc",
        "order": 13,
        "width": "6",
        "height": "3",
        "label": "Lautstärke",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1073,
        "y": 125,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "77f1919d.e6b84",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "18f5a3cf.c12dbc",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Termperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "40",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 1072,
        "y": 164,
        "wires": []
    },
    {
        "id": "1dc74cff.abb263",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "18f5a3cf.c12dbc",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperatur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1071,
        "y": 202,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "35f5f08.ee1651",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "18f5a3cf.c12dbc",
        "order": 6,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "65",
        "seg2": "70",
        "x": 1081,
        "y": 276,
        "wires": []
    },
    {
        "id": "b82e175f.ff76a8",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "18f5a3cf.c12dbc",
        "order": 7,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1079,
        "y": 311,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "1305073b.180619",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "CO2",
        "group": "18f5a3cf.c12dbc",
        "order": 8,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "CO2",
        "label": "PPM",
        "format": "{{value}}",
        "min": 0,
        "max": "5000",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "1000",
        "seg2": "2000",
        "x": 1049,
        "y": 347,
        "wires": []
    },
    {
        "id": "aea672ad.41199",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "CO2",
        "group": "18f5a3cf.c12dbc",
        "order": 9,
        "width": "6",
        "height": "3",
        "label": "CO2",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 1049,
        "y": 388,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "d091f10d.26b4",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "18f5a3cf.c12dbc",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1056,
        "y": 471,
        "wires": []
    },
    {
        "id": "a0f2d627.a87e48",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "18f5a3cf.c12dbc",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 1065,
        "y": 508,
        "wires": []
    },
    {
        "id": "12134281.6912fd",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "4b93141d.eb599c",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Temperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "40",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 379,
        "y": 452,
        "wires": []
    },
    {
        "id": "5beb13db.4fb49c",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "4b93141d.eb599c",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperatur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 379,
        "y": 487,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "d3d7895a.133a48",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "4b93141d.eb599c",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 365,
        "y": 632,
        "wires": []
    },
    {
        "id": "d509cc3f.9922c",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "4b93141d.eb599c",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 374,
        "y": 668,
        "wires": []
    },
    {
        "id": "7b84810f.594f",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "4b93141d.eb599c",
        "order": 0,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "60",
        "seg2": "65",
        "x": 388,
        "y": 558,
        "wires": []
    },
    {
        "id": "297a3afd.337986",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "4b93141d.eb599c",
        "order": 0,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 390,
        "y": 597,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "258e1ef9.a6b5a2",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "CO2",
        "group": "4b93141d.eb599c",
        "order": 0,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "CO2",
        "label": "ppm",
        "format": "{{value}}",
        "min": 0,
        "max": "5000",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "1000",
        "seg2": "1500",
        "x": 355,
        "y": 707,
        "wires": []
    },
    {
        "id": "dde7f0c1.0ef08",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "CO2",
        "group": "4b93141d.eb599c",
        "order": 0,
        "width": "6",
        "height": "3",
        "label": "CO2",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 355,
        "y": 749,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "322a090a.328106",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "5368deb4.54dba",
        "order": 1,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Temperatur",
        "label": "°C",
        "format": "{{value}}",
        "min": 0,
        "max": "50",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "25",
        "seg2": "30",
        "x": 820,
        "y": 382,
        "wires": []
    },
    {
        "id": "8d284696.050368",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Temperatur",
        "group": "5368deb4.54dba",
        "order": 2,
        "width": "6",
        "height": "3",
        "label": "Temperartur",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 818,
        "y": 417,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "3799e200.1d7f6e",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "5368deb4.54dba",
        "order": 4,
        "width": "3",
        "height": "1",
        "name": "Min Temp",
        "label": "Min Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 807,
        "y": 491,
        "wires": []
    },
    {
        "id": "1c1d6c41.73c5d4",
        "type": "ui_text",
        "z": "fd02760a.0d90c8",
        "group": "5368deb4.54dba",
        "order": 5,
        "width": "3",
        "height": "1",
        "name": "Max Temp",
        "label": "Max Temp",
        "format": "{{msg.payload}}",
        "layout": "col-center",
        "x": 817,
        "y": 531,
        "wires": []
    },
    {
        "id": "353985a1.6b0a6a",
        "type": "ui_gauge",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "5368deb4.54dba",
        "order": 6,
        "width": "3",
        "height": "3",
        "gtype": "gage",
        "title": "Luftfeuchtigkeit",
        "label": "%",
        "format": "{{value}}",
        "min": 0,
        "max": "100",
        "colors": [
            "#00b500",
            "#e6e600",
            "#ca3838"
        ],
        "seg1": "60",
        "seg2": "70",
        "x": 826,
        "y": 570,
        "wires": []
    },
    {
        "id": "6a103af.2e7cbc4",
        "type": "ui_chart",
        "z": "fd02760a.0d90c8",
        "name": "Luftfeuchtigkeit",
        "group": "5368deb4.54dba",
        "order": 7,
        "width": "6",
        "height": "3",
        "label": "Luftfeuchtigkeit",
        "chartType": "line",
        "legend": "false",
        "xformat": "HH:mm:ss",
        "interpolate": "linear",
        "nodata": "",
        "dot": false,
        "ymin": "",
        "ymax": "",
        "removeOlder": "24",
        "removeOlderPoints": "",
        "removeOlderUnit": "3600",
        "cutout": 0,
        "useOneColor": false,
        "colors": [
            "#1f77b4",
            "#aec7e8",
            "#ff7f0e",
            "#2ca02c",
            "#98df8a",
            "#d62728",
            "#ff9896",
            "#9467bd",
            "#c5b0d5"
        ],
        "x": 827,
        "y": 607,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "b71bfc6f.5b329",
        "type": "configNode",
        "z": "",
        "client_id": "yourclientid",
        "client_secret": "yourclientsecret",
        "username": "youremail",
        "password": "yourpassword",
        "device_id": "yourdeviceid"
    },
    {
        "id": "18f5a3cf.c12dbc",
        "type": "ui_group",
        "z": "",
        "name": "Wohnzimmer",
        "tab": "29ed66be.7ecb7a",
        "disp": true,
        "width": "9"
    },
    {
        "id": "4b93141d.eb599c",
        "type": "ui_group",
        "z": "",
        "name": "Schlafzimmer",
        "tab": "29ed66be.7ecb7a",
        "order": 2,
        "disp": true,
        "width": "9"
    },
    {
        "id": "5368deb4.54dba",
        "type": "ui_group",
        "z": "",
        "name": "Außen",
        "tab": "29ed66be.7ecb7a",
        "order": 3,
        "disp": true,
        "width": "9"
    },
    {
        "id": "29ed66be.7ecb7a",
        "type": "ui_tab",
        "z": "",
        "name": "Netatmo",
        "icon": "dashboard"
    }
]
